const DETERMINED_QUESTION_COUNT = 'game/DETERMINED_QUESTION_COUNT'
const ANSWERED_QUESTION = 'game/ANSWERED_QUESTION'
const RESET_GAME = 'game/RESET_GAME'

export default {
  DETERMINED_QUESTION_COUNT,
  ANSWERED_QUESTION,
  RESET_GAME,
}
