const FETCHING_TRIVIA = 'trivia/FETCHING_TRIVIA'
const FETCHING_TRIVIA_SUCCESS = 'trivia/FETCHING_TRIVIA_SUCCESS'
const FETCHING_TRIVIA_ERROR = 'trivia/FETCHING_TRIVIA_ERROR'
const RESET_TRIVIA = 'trivia/RESET_TRIVIA'

export default {
  FETCHING_TRIVIA,
  FETCHING_TRIVIA_SUCCESS,
  FETCHING_TRIVIA_ERROR,
  RESET_TRIVIA,
}
